Repository wecode-bootcamp-korea/14-1st-HOT-backend, pull requests merged in 2020-11, with the labels that each got.

#1 [House of Tomorrow] Add: models
  .DS_Store
  .gitignore
  housetomorrow/settings.py
  housetomorrow/urls.py
  order/__init__.py
  order/admin.py
  order/apps.py
  order/migrations/__init__.py
  order/models.py
  order/tests.py
  order/views.py
  post/__init__.py
  post/admin.py
  post/apps.py
  post/migrations/0001_initial.py
  post/migrations/0002_auto_20201118_1544.py
  post/migrations/__init__.py
  post/models.py
  post/tests.py
  post/views.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/views.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20201118_1544.py
  user/migrations/0003_auto_20201118_1924.py
  user/migrations/0004_auto_20201118_2028.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
Labels: Status: 리뷰 요청

#3 Add: User views - Register, SignIn / User utils - login_decorator
  .DS_Store
  .gitignore
  housetomorrow/urls.py
  order/migrations/0001_initial.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: 리뷰 요청

#4 [merge요청]models modified
  product/migrations/0002_auto_20201120_1750.py
  product/migrations/0003_auto_20201120_1752.py
  product/migrations/0004_auto_20201120_1755.py
  product/models.py
  user/migrations/0005_collectionbookmark.py
  user/models.py
Labels: Status: Accepted

#7 Add: GET-Post List 구현
  housetomorrow/urls.py
  post/migrations/0003_auto_20201121_1718.py
  post/models.py
  post/urls.py
  post/views.py
Labels: Status: 리뷰 요청

#15 Feature/ [수정] follow, unfollow 분리 구현
  user/urls.py
  user/views.py
Labels: Status: 수정 요청

#9 Add: PostDetailView 엔드포인트 생성 및 포스트 디테일 가져오기 구현
  post/urls.py
  post/views.py
Labels: Status: 리뷰 요청

#10 Add: 댓글 달기 엔드포인트 구현
  housetomorrow/urls.py
  post/urls.py
  post/views.py
  user/models.py
Labels: Status: 리뷰 요청

#28 Refactor: Post and Comment
  .gitignore
  housetomorrow/settings.py
  post/views.py
Labels: Status: 리뷰 요청

#31 Add: 코멘트 삭제 기능 및 GET method 작성
  post/urls.py
  post/views.py
Labels: Status: 리뷰 요청

#27 Feature/product sorting
  product/models.py
  product/views.py
Labels: Status: 리뷰 요청

#35 Add: 댓글 수정 기능 추가
  post/views.py
Labels: Status: 리뷰 요청

#34 Add: 포스트 수정기능 추가
  post/views.py
  user/views.py
Labels: Status: 리뷰 요청

#36 이거 머지해주세요!
  order/models.py
  order/urls.py
  order/views.py
Labels: Status: 리뷰 요청
